In [35]:
import pandas as pd
import numpy as np
from sklearn.utils import shuffle
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

In [36]:
df=pd.read_csv('Preprocessed Dataframe.csv', sep=chr(int("15")))
df

,NounVerbAdj,career,life,money,culture,manager,overall,sentiment
0,"['밸류', '인정', '받고', '방황', '하는']",3.0,3,3,3,2,2.8,neutral
1,"['들어온지', '마안', '됐지만', '좋아', '보여요']",5.0,5,5,5,5,5.0,positive
2,"['열정', '실력', '갖추는', '조직']",5.0,5,5,5,5,5.0,positive
3,"['로켓', '성장하는', '회사']",5.0,5,5,5,5,5.0,positive
4,"['워워벨', '보장', '되는', '회사']",4.0,3,5,5,3,4.0,positive
...,...,...,...,...,...,...,...,...
12295,"['다닐만', '회사']",3.0,3,4,3,3,3.2,neutral
12296,['팀바팀'],4.0,4,4,4,3,3.8,positive
12297,"['개임', '회사', '특성', '단점', '빼면', '좋음']",3.0,5,5,4,4,4.2,positive
12298,"['복지', '좋음']",2.0,3,4,2,1,2.4,negative
12299,"['복지', '좋은', '회사']",3.0,3,4,3,2,3.0,neutral

In [ ]:
#감성분석 (1)

In [37]:
sent_postive=df['sentiment']=='positive'
sent_negative=df['sentiment']=='negative'

In [38]:
df_positive=df[sent_postive].iloc[:,[0,7]]
df_negative=df[sent_negative].iloc[:,[0,7]]

In [39]:
df_train=pd.concat([df_positive, df_negative])
df_train=shuffle(df_train)

In [40]:
df_train

                                             NounVerbAdj sentiment
4356                         ['보여지는', '이미지', '다른', '회사']  negative
9102   ['불통', '팔이', '사원', '급여', '낮으니', '임원', '급여', '최고']  negative
8850                                      ['사람', '좋습니다']  positive
9985                                ['서비스', '하는', '대기업']  negative
208                           ['국내', '티어', '대기업', '아쉬움']  positive
...                                                  ...       ...
10239                               ['대한민국', '최고', '복지']  positive
11216                                ['주주', '만드는', '회사']  negative
4104                                  ['보장', '되는', '회사']  positive
4213                   ['라벨', '좋다', '주니어', '성장하기', '힘듬']  negative
4296                         ['유연한', '근무시간', '안식', '휴가']  positive

[8129 rows x 2 columns]

In [41]:
tf_vectorizer = CountVectorizer(min_df=1, ngram_range=(1,1)) 
tf_train_features = tf_vectorizer.fit_transform(df['NounVerbAdj'])

In [42]:
vocablist = [word for word, _ in sorted(tf_vectorizer.vocabulary_.items(), key=lambda x:x[1])]

In [43]:
lr_tf = LogisticRegression(max_iter=10000000)
lr_tf.fit(tf_train_features, df['sentiment'])

LogisticRegression(max_iter=10000000)

In [1]:
#(Sentiment Analysis.ipynb #감성분석 (2))

In [44]:
# Get coefficients of the model 
coefficients = lr_tf.coef_.tolist()

sorted_coefficients = sorted(enumerate(coefficients[0]), key=lambda x:x[1], reverse=True)
# 학습에 사용된 각 단어마다의 coefficient (즉 weight) 값이 존재
# coefficient값이 큰 순으로 정렬 'reverse=True'

print(sorted_coefficients[:5])
# print top 20 positive words
for word, coef in sorted_coefficients[:20]:
    print('{0:} ({1:.3f})'.format(vocablist[word], coef))
# print top 20 negative words
for word, coef in sorted_coefficients[-20:]:
    print('{0:} ({1:.3f})'.format(vocablist[word], coef))

[(5244, 1.6900785054466272), (4275, 1.64602631128778), (1652, 1.6082872001257165), (6103, 1.4629080129609346), (2629, 1.4317573504903385)]
최악 (1.690)
임원 (1.646)
루팡 (1.608)
힘들다 (1.463)
불통 (1.432)
개살구 (1.396)
나갈 (1.333)
관성 (1.312)
하위 (1.300)
낮고 (1.299)
사장 (1.286)
노예 (1.276)
명성 (1.270)
비추 (1.245)
침몰 (1.191)
관리직 (1.156)
오지마 (1.154)
거쳐가는 (1.150)
넣는 (1.145)
좋소 (1.143)
괜찮은데 (-0.995)
네이버 (-0.995)
나쁘지 (-1.015)
나름 (-1.015)
성장하기 (-1.032)
자유로운 (-1.043)
만족하는 (-1.044)
만족하며 (-1.077)
성장할 (-1.080)
불만 (-1.085)
성장하고 (-1.093)
최강 (-1.126)
좋은데 (-1.255)
나쁘진 (-1.259)
좋습니다 (-1.274)
만족스러운 (-1.295)
도전 (-1.335)
이만 (-1.434)
싶은 (-1.537)
만족 (-1.614)